Added preview animation in readme.md (#3)
SgiobairOg/color-vision pull request #8
Opened 2019-10-15 22:38 UTC by pradipta007

Added the given animation just after features section with alt text.

2019-10-16 06:52 UTC, pradipta007 commented
#8 @SgiobairOg Hi i have made the required changes :)

2019-10-16 13:51 UTC, SgiobairOg requested changes
Looks good, just need to move the text description. The quoted section after the url renders as a `title` attribute, the text in the square brackets is what renders as `alt` text.

2019-10-16 13:51 UTC, SgiobairOg commented on README.md
> +![alt text](resources/images/usage_15102019_512.gif "Example usage of the Color Vision extension showing color swatches being added to HEX and RGB color definitions")
```suggestion
![Example usage of the Color Vision extension showing color swatches being added to HEX and RGB color definitions](resources/images/usage_15102019_512.gif)
```

2019-10-16 18:13 UTC, pradipta007 commented on README.md
> +![alt text](resources/images/usage_15102019_512.gif "Example usage of the Color Vision extension showing color swatches being added to HEX and RGB color definitions")
was my updated readme.md file taken?

2019-10-17 12:17 UTC, SgiobairOg approved these changes
All good, thanks for contributing!

2019-10-17 12:18 UTC, merged